#!/usr/bin/env python3
# Copyright (c) 2026 OpenNVR
# SPDX-License-Identifier: Apache-2.0
"""Generate the site's derived pages from ``API_TIERS``.

One page per tier, one ``:::`` block per export, in the tier's own
order, plus the cookbook index with its links rewritten for the web.
Nothing here is hand-written: a name added to a tier appears on the
site without anyone remembering, and a name removed cannot leave a dead
page behind.

    python scripts/gen_reference.py            # write docs_src/
    python scripts/gen_reference.py --check    # fail if it would change
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from opennvr_adapter_sdk import API_TIERS  # noqa: E402

COOKBOOK_URL = (
    "https://github.com/open-nvr/ai-adapter/blob/main/cookbook/"
)

PAGE_TEXT: dict[str, tuple[str, str]] = {
    "front-door": (
        "Front door",
        "Four names. If you are publishing a model, this is the whole\n"
        "API — `Adapter` declares it, `@adapter.on_image` is the model,\n"
        "and `InferCall` is what each request arrives as. Everything\n"
        "else on this site is for the adapter that outgrows them.",
    ),
    "classes": (
        "The classes underneath",
        "`Adapter` compiles to these. Write them directly when a model\n"
        "needs more than the decorators give — several loading phases, a\n"
        "`/capabilities` that varies by host, or health semantics of its\n"
        "own. Same process, same endpoints, same published specs.",
    ),
    "identity": (
        "Identity and capability",
        "What `/capabilities` and `/health` say about the adapter and the\n"
        "model it wraps. KAI-C reads this to decide whether to route work\n"
        "here, and re-reads it to notice a model changing underneath a\n"
        "running deployment.",
    ),
    "answers": (
        "Answering",
        "The successful shape, and the failure taxonomy. The error\n"
        "category is not paperwork: KAI-C routes on it, so the difference\n"
        "between a `transport_error` and a `model_error` is the\n"
        "difference between one dropped frame and a retry storm.",
    ),
    "specs": (
        "Published specs",
        "The documents an adapter publishes about itself, generated from\n"
        "the contract types it actually returns.",
    ),
}


def page(slug: str, names: tuple[str, ...]) -> str:
    title, lede = PAGE_TEXT[slug]
    out = ["<!-- Generated by scripts/gen_reference.py — do not edit. -->",
           f"# {title}", "", lede, ""]
    for name in names:
        out += [f"::: opennvr_adapter_sdk.{name}", ""]
    return "\n".join(out).rstrip() + "\n"


COOKBOOK_HEADER = """<!-- Generated by scripts/gen_reference.py \
from cookbook/README.md — do not edit. -->
# Cookbook

One runnable file per class — how it is constructed or subclassed, and
which APIs it uses. Every file is imported and exercised by the SDK's
test suite, so an example that names something the SDK no longer
exports breaks in CI rather than misleading you months later.

"""


def cookbook_page(readme: str) -> str:
    body = readme.split("\n", 1)[1] if readme.startswith("# ") else readme
    marker = "## Write an adapter"
    body = body[body.index(marker):] if marker in body else body.lstrip()
    body = re.sub(r"\]\((\d\d_[a-z0-9_]+\.py)\)", rf"]({COOKBOOK_URL}\1)", body)
    return COOKBOOK_HEADER + body.rstrip() + "\n"


def write(path: Path, body: str, *, check: bool) -> bool:
    current = path.read_text(encoding="utf-8") if path.exists() else None
    if current == body:
        return False
    if not check:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(body, encoding="utf-8")
    return True


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    target = ROOT / "docs_src" / "reference"
    target.mkdir(parents=True, exist_ok=True)
    stale = False
    written = []
    for slug, names in API_TIERS.items():
        stale |= write(target / f"{slug}.md", page(slug, names), check=args.check)
        written.append(f"{slug}.md")

    stale |= write(
        ROOT / "docs_src" / "cookbook.md",
        cookbook_page((ROOT / "cookbook" / "README.md").read_text(encoding="utf-8")),
        check=args.check,
    )

    for orphan in target.glob("*.md"):
        if orphan.name not in written:
            stale = True
            if not args.check:
                orphan.unlink()

    if args.check and stale:
        print("reference pages are out of date — run "
              "`python scripts/gen_reference.py`", file=sys.stderr)
        return 1
    if not args.check:
        print(f"wrote {len(written)} reference pages + cookbook.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
